### ISSUE TITLE
bounding box?

### ISSUE THREAD

**Issue by strongh** [strongh/ClimateActionR#3]
Probably makes sense to have a standard bounding box for the region of interest. Roughly this could be the southwestern US. Something like 
- lat: from 31 to 42
- long: from -124 to -104

**Comment by wpetry** [comment]
Great.  Let's use a consistent coordinate system too.  Something like:
+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
